apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
  #may change according to kubernetes distribution
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pv01
