---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: ubuntu/prometheus:edge
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/alerts.yml
          subPath: alerts.yml
        - name: prometheus-data
          mountPath: /prometheus
        ports:
        - containerPort: 9090
          name: prometheus
          protocol: TCP
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
            items:
            - key: prometheus
              path: prometheus.yml
            - key: prometheus-alerts
              path: alerts.yml
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
    name: prometheus
