apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus"
