apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
spec:
  namespace: monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #may change according to kubernetes distribution
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: prometheus-pv
