apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
  - name: prometheus-container
    image: ubuntu/prometheus:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
    volumeMounts:
      - mountPath: /etc/prometheus
        name: prometheus-conf
    # - mountPath: "/prometheus"
    #   name: prometheus-pv

  volumes:
    - name: prometheus-conf
      configMap:
        name: prometheus-config
  # - name: prometheus-pv
  #   persistentVolumeClaim:
  #       claimName: prometheus-pv-claim
        
        
  