# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      #- 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alerts.yml'
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cevmkubernetes1'
    static_configs:
    - targets: ['10.7.1.86:9100']

  - job_name: 'cevmkubernetes2'
    static_configs:
    - targets: ['10.7.1.87:9100']

  - job_name: 'cevmkubernetes3'
    static_configs:
    - targets: ['10.7.1.88:9100']
  
  - job_name: 'cevmkubernetes-loadbalancer'
    static_configs:
    - targets: ['10.7.1.89:9100']
  
  - job_name: 'SEI-teste'
    static_configs:
    - targets: ['10.7.1.153:9100']
  
  - job_name: 'cevmdocker-hmg'
    static_configs:
    - targets: ['10.7.1.179:9100']
  
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
